version: '3.9'

services:
  server:
    build:
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./src/:/app/src/
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
    db_data:
      driver: local
