version: '3.9'

services:
  back:
    build:
      dockerfile: Dockerfile
      target: development
      context: back
    volumes:
      - /src/:/app/back/src/
    ports:
      - 8000:8000
    networks:
      - app
    depends_on:
      - db

  front:
    build:
      dockerfile: Dockerfile
      target: development
      context: front
    volumes:
      - /src/:/app/front/src/
      - node_modules:/app/front/node_modules/
    ports:
      - 3000:3000
    networks:
      - app
    depends_on:
      - back

  db:
    image: postgres:15-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - app
    environment:
      - POSTGRES_PASSWORD=password

networks:
  app:
    driver: bridge

volumes:
    db_data:
    node_modules:
